name: Build and Deploy CV to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Build PDF
        run: typst compile data_science.typ data_science.pdf

      - name: Convert PDF to HTML
        run: |
          # Install pdf2htmlEX
          sudo apt-get update
          sudo apt-get install -y pdf2htmlex
          
          # Convert PDF to HTML
          pdf2htmlEX --zoom 1.3 --dest-dir . data_science.pdf
          
          # Create a simple HTML wrapper
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="fr">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>CV - Yann Sadowski - Data Science</title>
              <style>
                  body {
                      margin: 0;
                      padding: 20px;
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                      background-color: #f5f5f5;
                  }
                  .container {
                      max-width: 1200px;
                      margin: 0 auto;
                      background-color: white;
                      box-shadow: 0 0 20px rgba(0,0,0,0.1);
                      border-radius: 8px;
                      overflow: hidden;
                  }
                  .header {
                      background-color: #26428b;
                      color: white;
                      padding: 20px;
                      text-align: center;
                  }
                  .header h1 {
                      margin: 0;
                      font-size: 2.5em;
                  }
                  .header p {
                      margin: 10px 0 0 0;
                      font-size: 1.2em;
                      opacity: 0.9;
                  }
                  .cv-frame {
                      width: 100%;
                      min-height: 800px;
                      border: none;
                      display: block;
                  }
                  .download-section {
                      padding: 20px;
                      text-align: center;
                      background-color: #f8f9fa;
                      border-top: 1px solid #e9ecef;
                  }
                  .download-btn {
                      display: inline-block;
                      padding: 12px 30px;
                      background-color: #26428b;
                      color: white;
                      text-decoration: none;
                      border-radius: 5px;
                      font-weight: bold;
                      transition: background-color 0.3s;
                  }
                  .download-btn:hover {
                      background-color: #1e356a;
                  }
                  @media (max-width: 768px) {
                      body {
                          padding: 10px;
                      }
                      .header h1 {
                          font-size: 2em;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>Yann Sadowski</h1>
                      <p>CV - Data Science</p>
                  </div>
                  
                  <iframe src="data_science.html" class="cv-frame" id="cv-frame"></iframe>
                  
                  <div class="download-section">
                      <a href="data_science.pdf" class="download-btn" download>
                          📄 Télécharger le CV (PDF)
                      </a>
                  </div>
              </div>
              
              <script>
                  // Auto-resize iframe to fit content
                  function resizeIframe() {
                      const iframe = document.getElementById('cv-frame');
                      try {
                          iframe.style.height = iframe.contentWindow.document.documentElement.scrollHeight + 'px';
                      } catch (e) {
                          // Fallback height if cross-origin issues
                          iframe.style.height = '1200px';
                      }
                  }
                  
                  document.getElementById('cv-frame').onload = resizeIframe;
                  window.addEventListener('resize', resizeIframe);
              </script>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4